"""Initial migration

Revision ID: b7096b61cc10
Revises: 725f82522962
Create Date: 2025-08-30 22:17:12.703432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7096b61cc10'
down_revision: Union[str, Sequence[str], None] = '725f82522962'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('imgUrl', sa.String(length=255), nullable=True))
    op.drop_column('cards', 'img')
    op.add_column('events', sa.Column('imgUrl', sa.String(length=255), nullable=True))
    op.add_column('players', sa.Column('avatarUrl', sa.String(length=255), nullable=True))
    op.add_column('players', sa.Column('role', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players', 'role')
    op.drop_column('players', 'avatarUrl')
    op.drop_column('events', 'imgUrl')
    op.add_column('cards', sa.Column('img', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('cards', 'imgUrl')
    # ### end Alembic commands ###
